# Generated by Django 5.1.1 on 2024-09-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massege',
            new_name='message',
        ),
    ]
