# Generated by Django 5.1.1 on 2024-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_alter_contact_email_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
