# Generated by Django 5.1.1 on 2024-09-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
