# Generated by Django 5.1.1 on 2024-10-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat_id',
            new_name='cat_id_1',
        ),
    ]
