# Generated by Django 5.1.1 on 2024-10-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_coupon_expiry_date_coupon_one_time_use_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('Postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('Mobile', models.IntegerField(blank=True, max_length=12, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('create_account', models.BooleanField(default=False)),
                ('ship_to_different_address', models.BooleanField(default=False)),
                ('Order_note', models.TextField(default='')),
            ],
        ),
    ]
