# Generated by Django 5.1.1 on 2024-10-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_billing_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing_details',
        ),
    ]
