# Generated by Django 5.1.1 on 2024-10-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_billing_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Company_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Address', models.CharField(blank=True, max_length=40, null=True)),
                ('City', models.CharField(blank=True, max_length=40, null=True)),
                ('Country', models.CharField(blank=True, max_length=40, null=True)),
                ('Postcode', models.CharField(blank=True, max_length=12, null=True)),
                ('Mobile', models.IntegerField(blank=True, max_length=12, null=True)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
