# Generated by Django 5.1.1 on 2024-10-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_billing_details_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Company_Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Address', models.CharField(blank=True, max_length=40, null=True)),
                ('City', models.CharField(blank=True, max_length=40, null=True)),
                ('Country', models.CharField(blank=True, max_length=40, null=True)),
                ('Postcode', models.CharField(blank=True, max_length=12, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Billing_details',
        ),
    ]
